name: llm
channels:
- nvidia
- pkgs/main
- pytorch
dependencies:
- python=3.9
- _libgcc_mutex
- _openmp_mutex
- annotated-types
- anyio
- blas
- boto3
- botocore
- brotli-python
- bzip2
- ca-certificates
- certifi
- charset-normalizer
- click
- cuda-cudart
- cuda-cupti
- cuda-libraries
- cuda-nvrtc
- cuda-nvtx
- cuda-opencl
- cuda-runtime
- cuda-version
- fastapi
- ffmpeg
- filelock
- freetype
- gmp
- gmpy2